### ISSUE TITLE
Is there a way to close o exit the program?

### ISSUE THREAD

**Issue by DarkXDroid** [gabrielmagno/nano-dlna#4]
I love this program but I'm having a problem while trying to close it... It seems that the only way for me to close is by killin the process with killall nanodlna. Not even "ctrl + c" works! Anyway thanks for this piece of code

**Comment by gabrielmagno** [comment]
I should definitely handle signals such as SIGINT (Ctrl + C) in the future. I think the proper behaviour in this case would be to send a STOP to the device and then exit nanodlna.

But I'm curious, because the actual behaviour for me when hitting Ctrl + C is that nanodlna is closed, but the video continues playing in the device.

What is your operational system and python version?

**Comment by DarkXDroid** [comment]
Python version: Python 2.7.13
Linux distro: Arch 

Output of uname: Linux CorePC 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux

**Comment by gabrielmagno** [comment]
I've just verified that the behaviour for hitting Ctrl + C is different for Python 2 and Python 3. In Python 2 it goes just as you described. With Python 3 it properly closes the program (although not stopping the video).

I will mark this as an enhancement request, so that I will investigate and implement a solution.

**Comment by DarkXDroid** [comment]
Silly me I thought It was compatible only with python 2.7 as it works well in that version. Alright thanks for your support in attending my claim.
